---
title: "My Little Corner of Space-Time in the Digital Universe"
subtitle: 'About Physics, Education, Programming and Other Such Stuff'
---

# Now that you are here...

Hello! I am a university educator who teaches physics and programming. Welcome to this digital space where my realities of physics, computing, and teaching super-pose.  I am deeply interested in understanding how we, as 'bags of water,' learn and think so that I can be a better mentor and educator. 

This site is inspired by my (wise beyond his years) brother, [Romesh](https://www.linkedin.com/in/romesh-udalagama/?originalSubdomain=au)'s suggestion to "work out loud."  The truth is, I am sorry to say this website is meant more for me than for you. Here are some objectives I would like to achieve through this space.

- Clarification and refinement of content and thought one gains from writing things down, 
- A digital space that can be a dynamic repository where I can find my stuff easily! 
- An opportunity to share what I have learned so that it might be helpful to someone who accidentally wandered into this unregarded site *far out in the uncharted backwaters of the unfashionable end* of the internet.

